### PR TITLE
Update contributors.txt

### PR DESCRIPTION
**Pull request by TonyLek**

### CODE REVIEW

**Comment by yossigil** [comment]
Your nick is not ood.

**Comment by tonylekhtman** [comment]
@yossigil  This one is ok?

**Comment by yossigil** [comment]
What's your real name?

**Comment by tonylekhtman** [comment]
My full name is entony, but i go by tony.

**Comment by OriRoth** [comment]
@yossigil https://www.facebook.com/tony.lekhtman

**Comment by yossigil** [comment]
:+1:

**Pull request merged**
