### PR TITLE
YuvalSimon

### PR DESCRIPTION
**Pull request by yuval250**
@AdiOmari

### CODE REVIEW

**Comment by yossigil** [comment]
Try to find a better avatar please

**Comment by yuval250** [comment]
Does my new avatar is better?

**Comment by yossigil** [comment]
It is find, just like mine, if only you have sufficient data to show that people know you by this name. If you do not want to put your face, you might want to be  creative so that the avatar is identified with you.

**Comment by yuvalsimon** [comment]
> It is find, just like mine, if only you have sufficient data to show that people know you by this name. If you do not want to put your face, you might want to be creative so that the avatar is identified with you.

Done. I haven't received yet invitation to the project so I can not assign myself to a new issue. @yossigil

**Comment by yossigil** [comment]
You did not because your name was not ok.

**Pull request merged**
