### PR TITLE
Update File

### PR DESCRIPTION
**Pull request by ylevv**
Added "Yarden Lev" to the list.
@AdiOmari

### CODE REVIEW

**Comment by orimarco** [comment]
@ylevv are you a cat?

**Comment by ylevv** [comment]
@orimarco Do I need to change the avatar?

**Comment by SharonKL** [comment]
@orimarco could you add me to the repository as well? :)

**Comment by SharonKL** [comment]
@AdiOmari yes, it was accepted by @OriRoth

**Comment by ylevv** [comment]
@orimarco no longer a cat

**Pull request merged**
